### ISSUE TITLE
Installation fails on missing file

### ISSUE THREAD

**Issue by guysoft** [danleyb2/php2python#2]
```
pip3 install convert2php
Collecting convert2php
  Downloading https://files.pythonhosted.org/packages/30/ba/afea59e34b8493c3318251a299c4fbb4aa132981b1f1a29478a9b5f69183/convert2php-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1w2wn_n9/convert2php/setup.py", line 9, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'README.md')) as readme:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-1w2wn_n9/convert2php/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1w2wn_n9/convert2php/
```

**Comment by digihash** [comment]
I have the same issue on my system, an ubuntu 14:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aVYPQ0/convert2php/

**Comment by guysoft** [comment]
Ok had a look, it looks like the problem is when running:
```
pip3 install convert2php
```

That fails because it uses
https://files.pythonhosted.org/packages/30/ba/afea59e34b8493c3318251a299c4fbb4aa132981b1f1a29478a9b5f69183/convert2php-0.0.1.tar.gz

which indeed does not have README.md

If you run:
```
pip3 install https://github.com/danleyb2/php2python/archive/master.zip
```
It works fine. So @danleyb2 needs to update the pypi module
